# Spring Boot应用的配置文件，包含了数据库连接、日志级别、文件上传限制等设置。
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  application:
    name: blog-back-end
  #  配置Mysql数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: YOUR_PASSWORD
  # Redis配置
  data:
    redis:
      host: localhost           # Redis 服务器地址
      port: 6379               # Redis 服务器连接端口
      password: YOUR_PASSWORD               # Redis 服务器连接密码（默认为空）
      database: 1              # Redis 数据库索引（选择数据库 1）
      connect-timeout: 10000   # 连接超时时间（毫秒）
      client-type: lettuce     # 使用 lettuce 客户端
      lettuce:
        pool:
          enabled: true        # 启用连接池
          max-active: 8        # 连接池最大连接数
          max-wait: -1ms       # 连接池最大阻塞等待时间（负值表示没有限制）
          max-idle: 8          # 连接池中的最大空闲连接
          min-idle: 0          # 连接池中的最小空闲连接
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # RabbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    virtual-host: /yblog
    username: yblog
    password: 123456
    listener:
      simple:
        acknowledge-mode: auto # 确认模式: auto(自动), manual(手动), none(无)
        prefetch: 10           # 每次预取消息数量
        concurrency: 5         # 最小消费者线程数
        max-concurrency: 10    # 最大消费者线程数
        retry:
          enabled: true        # 开启消费重试
          max-attempts: 3      # 最大重试次数
          initial-interval: 1000 # 重试间隔(ms)


# MyBatis-Plus的配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 日志的配置
logging:
  level:
    # 关闭 RMI 相关的 DEBUG 日志
    sun.rmi: INFO
    javax.management: INFO
    com.sun.jmx: INFO

    # 关闭其他可能的噪音日志
    org.springframework: INFO
    org.hibernate: INFO
    org.jboss: INFO

    # 只保留你的应用日志为 DEBUG
    blogsystem: DEBUG

    # 设置根日志级别
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 云服务存储的配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: y-37
    region: cn-beijing
